"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, BadgeCheck, BookOpen, Bookmark, Check, ChevronDown, Clapperboard, FileCheck2, Gift, Handshake, LibraryBig, Loader2, Menu, PenLine, Search, ShieldCheck, SlidersHorizontal, Sparkles, X } from "lucide-react";
import { Brand } from "./brand";
import { Modal, StatusBadge, Toast } from "./ui";
import { WorkCard } from "./work-card";
import { OrderDialog, WorkDetail } from "./work-dialogs";
import { errorMessage, requestJSON } from "@/lib/client";
import { formatSections, formatsForSection, genres, money, sectionForFormat, type PublicProfile, type PublicWork, type StoreSection } from "@/lib/types";

type Dialog = { type: "detail"; work: PublicWork } | { type: "order"; work: PublicWork; action: "buy" | "hold" } | { type: "saved" } | null;
type SectionChoice = StoreSection | "all";
const sectionIcons: Record<StoreSection, typeof Clapperboard> = { script: Clapperboard, ebook: BookOpen, library: LibraryBig };

function StoreNavigation({ active, choose }: { active: SectionChoice; choose: (section: StoreSection, format?: string) => void }) {
  return <nav className="desktop-nav store-navigation" aria-label="Jenis koleksi">
    {(Object.keys(formatSections) as StoreSection[]).map((section) => {
      const item = formatSections[section];
      const Icon = sectionIcons[section];
      return <details key={section} className={`store-menu${active === section ? " active" : ""}`}>
        <summary><Icon size={14} />{item.label}<ChevronDown size={12} /></summary>
        <div className="store-menu-popover"><p>{item.eyebrow}</p>{item.formats.map((format) => <button key={format} onClick={() => choose(section, format)}>{format}<ArrowUpRight size={12} /></button>)}</div>
      </details>;
    })}
    <a href="https://mayamyrapenulisblog.blogspot.com/" target="_blank" rel="noopener noreferrer" className="nav-link nav-free-zone"><Gift size={13} style={{ display: "inline", verticalAlign: "middle", marginRight: "5px" }} />Zon Bacaan Percuma (Blog) <ArrowUpRight size={12} style={{ display: "inline", verticalAlign: "middle" }} /></a>
    <a href="#tentang" className="nav-link">Tentang penulis</a>
  </nav>;
}

function HeroArtwork({ work, count, onOpen }: { work?: PublicWork; count: number; onOpen: () => void }) {
  return <div className="hero-artwork"><div className="artwork-grain" /><span className="scene-note">Cerita yang menunggu<br />untuk dihidupkan.</span><span className="scene-edition">MAYA MYRA<br />STORY COLLECTION</span><svg className="scene-star" viewBox="0 0 70 70" fill="none" aria-hidden="true"><path d="M35 3v64M3 35h64M12.4 12.4l45.2 45.2m0-45.2L12.4 57.6M22.7 5.4l24.6 59.2M5.4 22.7l59.2 24.6m0-24.6L5.4 47.3M47.3 5.4 22.7 64.6" stroke="currentColor" strokeWidth="1.2" /></svg><div className="paper-back paper-back-one"><span>KARYA ORIGINAL</span><i /><i /><i /><i /><i /></div><div className="paper-back paper-back-two" /><button className="hero-manuscript" onClick={onOpen} aria-label={`Pratonton ${work?.title || "karya pilihan"}`}><span className="paper-topline"><span>MAYA MYRA STORIES</span><span>NO. 001</span></span><span className="paper-category">{work?.format.toUpperCase() || "SKRIP TEATER"}</span><span className="paper-title">{work?.title || <>Teater Tun<br />Teja.</>}</span><span className="paper-description">SEBUAH CERITA UNTUK DIHIDUPKAN.</span><img className="paper-photo" src={work?.image || "/images/tun-teja.jpg"} alt="Kulit karya pilihan" /><span className="paper-footer"><span>OLEH {work?.author.toUpperCase() || "MAYA MYRA"}</span><span>01 — {String(count).padStart(2, "0")}</span></span></button><svg className="scene-leaf" viewBox="0 0 150 175" fill="none" aria-hidden="true"><path d="M28 165C53 140 71 107 91 24" stroke="currentColor" strokeWidth="1.5" /><path d="M60 123C28 117 20 102 15 83c32 0 48 14 45 40Zm13-29C39 84 42 67 44 53c26 9 36 22 29 41Zm10-32C64 40 71 24 84 11c13 21 17 35-1 51Zm-27 75c37 0 51-10 67-31-31-10-54 4-67 31Zm20-40c30 2 50-13 57-35-26-4-45 10-57 35Zm12-34c28-6 35-22 36-40-23 5-34 18-36 40Z" fill="currentColor" fillOpacity=".14" stroke="currentColor" strokeWidth="1" /></svg><div className="editor-note"><span><Sparkles size={13} /> PILIHAN PENULIS</span></div><div className="original-note"><span className="original-icon"><FileCheck2 size={23} strokeWidth={1.5} /></span><div><strong>Karya asli. Cerita anda.</strong><span>Hak eksklusif, terus dari penulis.</span></div><BadgeCheck size={17} /></div></div>;
}

function Newsletter() {
  const [loading, setLoading] = useState(false), [done, setDone] = useState(false), [error, setError] = useState("");
  async function subscribe(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); try { await requestJSON("/api/newsletter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: new FormData(event.currentTarget).get("email") }) }); setDone(true); } catch (err) { setError(errorMessage(err)); } finally { setLoading(false); } }
  return <section className="newsletter-section container"><div><span className="eyebrow">SURAT KECIL DARI MAYA MYRA</span><h2>Jangan terlepas cerita baharu.</h2><p>Daftarkan minat anda untuk karya baharu, bahan bacaan percuma dan nota daripada penulis.</p></div><div className="newsletter-form-wrap">{done ? <div className="subscription-success" role="status"><Check size={22} /><div><strong>Anda sudah dalam senarai.</strong><span>Terima kasih kerana menjadi sebahagian daripada cerita ini.</span></div></div> : <form className="newsletter-form" onSubmit={subscribe}><label className="sr-only" htmlFor="newsletter-email">Alamat e-mel</label><input id="newsletter-email" name="email" type="email" placeholder="Alamat e-mel anda" maxLength={254} required /><button className="button" disabled={loading}>{loading ? <Loader2 size={17} className="spin" /> : <>Daftar minat <ArrowUpRight size={16} /></>}</button></form>}{error && <p className="form-error" role="alert">{error}</p>}<p className="newsletter-small">Hanya cerita yang baik. Tiada spam.</p></div></section>;
}

const faqs = [
  { question: "Apa maksud BUY NOW, HOLD dan SOLD OUT?", answer: "BUY NOW menandakan karya sedia dibeli dan menghantar permintaan pembelian kepada penulis. HOLD menahan satu karya mengikut tempoh yang tertera untuk perbincangan eksklusif. SOLD OUT bermaksud hak cipta karya telah dijual secara rasmi dan tidak lagi tersedia." },
  { question: "Adakah BUY NOW terus membuka muat turun?", answer: "Belum dalam versi ini. BUY NOW menghantar permintaan kepada penulis; pembayaran dan perjanjian hak disahkan secara terus dahulu. Selepas penulis mengesahkan jualan, pautan muat turun pembeli dibuka. Pembayaran dan muat turun automatik boleh ditambah kemudian dengan gateway pembayaran." },
  { question: "Apa itu Perpustakaan Percuma?", answer: "Ia ialah zon bacaan tanpa Buy atau Hold: tiga bab pertama e-book, draf pitching skrip dan cerpen mingguan. Pembaca boleh membukanya terus. Jangan letakkan fail penuh berbayar dalam zon ini." },
  { question: "Bolehkah saya membeli skrip atau e-book?", answer: "Boleh. Kedai Skrip menempatkan karya untuk produksi seperti drama bersiri, telefilem, filem cereka, siri digital, teater dan radio. Kedai E-Book pula untuk bahan pembaca seperti fiksyen, bukan fiksyen dan panduan penulisan." },
  { question: "Adakah pemilik lain boleh upload karya?", answer: "Tidak. Ini laman peribadi seorang penulis. Butang dan API upload hanya tersedia selepas pemilik laman log masuk ke Ruang Penulis." },
];

export function Marketplace({ initialWorks, profile, isOwner = false }: { initialWorks: PublicWork[]; profile: PublicProfile; isOwner?: boolean }) {
  const [works, setWorks] = useState(initialWorks);
  const [section, setSection] = useState<SectionChoice>("all");
  const [category, setCategory] = useState("all");
  const [query, setQuery] = useState("");
  const [genre, setGenre] = useState("all"), [status, setStatus] = useState("all"), [progress, setProgress] = useState("all"), [sort, setSort] = useState("recommended");
  const [showAll, setShowAll] = useState(false), [filtersOpen, setFiltersOpen] = useState(false), [mobileOpen, setMobileOpen] = useState(false);
  const [saved, setSaved] = useState<string[]>([]), [dialog, setDialog] = useState<Dialog>(null), [toast, setToast] = useState("");
  const [faqOpen, setFaqOpen] = useState<number | null>(null);
  const filterRef = useRef<HTMLDivElement>(null);
  const closeDialog = useCallback(() => setDialog(null), []);
  const closeToast = useCallback(() => setToast(""), []);
  useEffect(() => { try { const stored = JSON.parse(localStorage.getItem("mayamyrastories_saved") || localStorage.getItem("naskah_saved") || "[]"); if (Array.isArray(stored)) setSaved(stored.filter((item) => typeof item === "string")); } catch { /* Browser storage is optional. */ } }, []);
  useEffect(() => { let active = true; const sync = () => { if (document.visibilityState !== "visible") return; requestJSON<{ works: PublicWork[] }>("/api/works").then((data) => { if (active) setWorks(data.works); }).catch(() => undefined); }; const timer = setInterval(sync, 30000); window.addEventListener("focus", sync); return () => { active = false; clearInterval(timer); window.removeEventListener("focus", sync); }; }, []);
  useEffect(() => { if (!filtersOpen) return; const close = (event: MouseEvent) => { if (!filterRef.current?.contains(event.target as Node)) setFiltersOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, [filtersOpen]);
  const visibleSaved = saved.filter((id) => works.some((work) => work.id === id));
  const selectedSection = section === "all" ? null : formatSections[section];
  function browse(nextSection: StoreSection, format = "all") { setSection(nextSection); setCategory(format); setShowAll(true); setMobileOpen(false); }
  function resetFilters() { setSection("all"); setCategory("all"); setGenre("all"); setStatus("all"); setProgress("all"); setQuery(""); setSort("recommended"); setShowAll(false); }
  function toggleSave(id: string) { const next = saved.includes(id) ? saved.filter((item) => item !== id) : [...saved, id]; setSaved(next); try { localStorage.setItem("mayamyrastories_saved", JSON.stringify(next)); } catch { /* Optional browser storage. */ } setToast(next.includes(id) ? "Karya ditambah ke simpanan." : "Karya dikeluarkan daripada simpanan."); }
  const filtered = useMemo(() => { const result = works.filter((work) => (section === "all" || work.section === section) && (category === "all" || work.format === category) && (genre === "all" || work.genre === genre) && (status === "all" || work.status === status) && (progress === "all" || work.progress === progress) && `${work.title} ${work.synopsis} ${work.genre} ${work.format} ${work.author}`.toLowerCase().includes(query.toLowerCase().trim())); return result.sort((a, b) => sort === "price-asc" ? a.price - b.price : sort === "price-desc" ? b.price - a.price : sort === "newest" ? b.createdAt.localeCompare(a.createdAt) : Number(a.isDemo) - Number(b.isDemo) || Number(b.featured) - Number(a.featured) || b.createdAt.localeCompare(a.createdAt)); }, [works, section, category, genre, status, progress, sort, query]);
  const visibleWorks = showAll ? filtered : filtered.slice(0, 4);
  const filterCount = Number(genre !== "all") + Number(status !== "all") + Number(progress !== "all");
  const author = profile.displayName || works[0]?.author || "Maya Myra";
  function openOrder(work: PublicWork, action: "buy" | "hold") { setDialog({ type: "order", work, action }); }
  function markReserved(id: string) { setWorks((current) => current.map((work) => work.id === id ? { ...work, status: "hold" } : work)); }

  return <><header className="site-header"><div className="header-inner container"><Brand /><StoreNavigation active={section} choose={browse} /><div className="header-actions"><button className="header-bookmark" aria-label={`Karya disimpan, ${visibleSaved.length} naskah`} onClick={() => setDialog({ type: "saved" })}><Bookmark size={20} strokeWidth={1.6} />{visibleSaved.length > 0 && <span>{visibleSaved.length}</span>}</button>{isOwner && <><span className="header-divider" /><Link className="button writer-link" href="/studio?upload=1"><PenLine size={15} />Ruang penulis<ArrowUpRight size={16} /></Link></>}<button className="icon-button mobile-menu-button" aria-label={mobileOpen ? "Tutup menu" : "Buka menu"} aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X size={23} /> : <Menu size={23} />}</button></div></div>{mobileOpen && <nav className="mobile-nav" aria-label="Navigasi mudah alih">{(Object.keys(formatSections) as StoreSection[]).map((key) => <button key={key} onClick={() => browse(key)}>{formatSections[key].label}<ArrowRight size={15} /></button>)}<a href="https://mayamyrapenulisblog.blogspot.com/" target="_blank" rel="noopener noreferrer" className="mobile-free-link" onClick={() => setMobileOpen(false)}><Gift size={14} style={{ display: "inline", verticalAlign: "middle", marginRight: "6px" }} />Zon Bacaan Percuma (Blog) <ArrowUpRight size={15} style={{ display: "inline", verticalAlign: "middle" }} /></a><a href="#tentang" onClick={() => setMobileOpen(false)}>Tentang penulis</a>{profile.blogUrl && <a href={profile.blogUrl} target="_blank" rel="noopener noreferrer">Catatan di blog <ArrowUpRight size={16} /></a>}{isOwner && <Link href="/studio">Ruang penulis <ArrowUpRight size={16} /></Link>}</nav>}</header>
    <main><section className="hero-section"><div className="hero-inner container"><div className="hero-copy"><div className="hero-kicker"><span />MAYA MYRA STORIES</div><h1>Cerita yang baik,<br /><em>bermula di sini.</em></h1><p>Skrip untuk produksi, e-book untuk pembaca dan<br className="desktop-break" /> perpustakaan kecil untuk sesiapa yang mahu membaca.</p><div className="hero-buttons"><a className="button hero-primary" href="#karya">Terokai karya <ArrowUpRight size={18} /></a><a className="button button-outline hero-free-zone" href={profile.blogUrl || "https://mayamyrapenulisblog.blogspot.com/"} target="_blank" rel="noopener noreferrer">Zon Bacaan Percuma (Blog) <ArrowUpRight size={16} /></a></div><div className="hero-stats"><div><strong>{String(works.filter((work) => work.section === "script").length).padStart(2, "0")}</strong><span>Skrip produksi</span></div><div><strong>{String(works.filter((work) => work.section === "ebook").length).padStart(2, "0")}</strong><span>E-book pilihan</span></div><div><strong>{String(works.filter((work) => work.isFree).length).padStart(2, "0")}</strong><span>Bacaan percuma</span></div></div></div><HeroArtwork work={works[0]} count={works.length} onOpen={() => { if (works[0]) setDialog({ type: "detail", work: works[0] }); }} /></div></section><div className="trust-strip"><div className="container trust-inner"><span><BadgeCheck size={18} strokeWidth={1.5} />Karya asli, suara sendiri</span><span><ShieldCheck size={18} strokeWidth={1.5} />Hak cipta dilindungi</span><span><Handshake size={19} strokeWidth={1.5} />Terus daripada penulis</span><span><BookOpen size={18} strokeWidth={1.5} />Skrip, e-book & bacaan free</span></div></div>
      <section className="shop-directory container" aria-label="Tiga bahagian koleksi">{(Object.keys(formatSections) as StoreSection[]).map((key) => { const item = formatSections[key]; const Icon = sectionIcons[key]; return <button key={key} onClick={() => browse(key)} className={`shop-directory-card shop-${key}`}><Icon size={25} /><span>{item.eyebrow}</span><h2>{item.label}</h2><p>{key === "script" ? "Drama bersiri, telefilem, filem cereka, teater dan siri digital." : key === "ebook" ? "Fiksyen, bukan fiksyen dan panduan untuk dibaca sendiri." : "3 bab pertama, draf pitching dan cerpen mingguan tanpa bayaran."}</p><strong>{key === "library" ? "Baca terus di sini / blog" : "Terokai koleksi"}<ArrowUpRight size={15} /></strong></button>; })}</section>
      <section className="catalog-section container" id="karya"><div className="section-heading"><div><p className="eyebrow">{selectedSection?.eyebrow || "SEMUA KOLEKSI"}</p><h2>{selectedSection?.label || "Temui cerita seterusnya."}</h2></div><button className="section-link" onClick={() => { resetFilters(); setShowAll(true); }}>Lihat semua karya <ArrowUpRight size={17} /></button></div>
        <div className="shop-tabs" role="tablist"><button role="tab" aria-selected={section === "all"} className={section === "all" ? "selected" : ""} onClick={() => { setSection("all"); setCategory("all"); setShowAll(false); }}>Semua koleksi</button>{(Object.keys(formatSections) as StoreSection[]).map((key) => <button role="tab" key={key} aria-selected={section === key} className={section === key ? "selected" : ""} onClick={() => browse(key)}>{formatSections[key].label}</button>)}</div>
        {section !== "all" && <div className="filter-tabs section-format-tabs" aria-label="Kategori format"><button className={`filter-tab${category === "all" ? " selected" : ""}`} onClick={() => setCategory("all")}>Semua {selectedSection?.label}</button>{formatsForSection(section).map((format) => <button key={format} className={`filter-tab${category === format ? " selected" : ""}`} onClick={() => { setCategory(format); setShowAll(true); }}>{format}</button>)}</div>}
        {section === "library" && <div className="blog-library-callout"><BookOpen size={20} /><div><strong>Zon Bacaan Percuma di Blog Maya Myra</strong><p>Cerpen mingguan dan catatan santai turut dikongsi secara terus di blog. Anda boleh membaca di sini atau terus ke blog.</p></div><a className="button button-outline" href={profile.blogUrl || "https://mayamyrapenulisblog.blogspot.com/"} target="_blank" rel="noopener noreferrer">Buka Zon Bacaan di Blog <ArrowUpRight size={14} /></a></div>}
        <div className="catalog-toolbar"><div className="catalog-tools"><div className="search-box"><Search size={17} strokeWidth={1.7} /><input aria-label="Cari naskah" placeholder="Cari tajuk, tema…" value={query} onChange={(event) => { setQuery(event.target.value); setShowAll(true); }} />{query && <button aria-label="Kosongkan carian" onClick={() => setQuery("")}><X size={14} /></button>}</div><div className="filter-wrap" ref={filterRef}><button className={`filter-button${filtersOpen || filterCount ? " filter-active" : ""}`} onClick={() => setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}><SlidersHorizontal size={16} />Tapis{filterCount > 0 && <span>{filterCount}</span>}</button>{filtersOpen && <div className="filter-popover"><h3>Temui karya anda</h3><label className="field">Genre / tema<select value={genre} onChange={(event) => { setGenre(event.target.value); setShowAll(true); }}><option value="all">Semua genre</option>{genres.map((item) => <option key={item}>{item}</option>)}</select></label>{section !== "library" && <><label className="field">Status karya<select value={status} onChange={(event) => { setStatus(event.target.value); setShowAll(true); }}><option value="all">Semua status</option><option value="available">BUY NOW</option><option value="hold">HOLD</option><option value="sold">SOLD OUT</option></select></label><label className="field">Tahap siap<select value={progress} onChange={(event) => { setProgress(event.target.value); setShowAll(true); }}><option value="all">Semua tahap</option><option value="Lengkap">Lengkap</option><option value="Separuh siap">Separuh siap</option></select></label></>}<label className="field">Susunan<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="recommended">Pilihan penulis</option><option value="newest">Paling baharu</option><option value="price-asc">Harga: rendah ke tinggi</option><option value="price-desc">Harga: tinggi ke rendah</option></select></label><div className="filter-popover-footer"><button onClick={resetFilters}>Set semula</button><button className="button" onClick={() => setFiltersOpen(false)}>Lihat {filtered.length} karya <Check size={14} /></button></div></div>}</div></div></div>
        {(query || filterCount > 0) && <div className="filter-results"><span>{filtered.length} karya ditemui{query && <> untuk “{query}”</>}</span><button onClick={resetFilters}>Kosongkan penapis <X size={12} /></button></div>}
        {visibleWorks.length ? <div className="works-grid">{visibleWorks.map((work) => <WorkCard key={work.id} work={work} saved={saved.includes(work.id)} onSave={toggleSave} onDetail={(selected) => setDialog({ type: "detail", work: selected })} onOrder={openOrder} />)}</div> : <div className="catalog-empty"><Search size={33} strokeWidth={1.3} /><h3>Belum bertemu cerita yang tepat?</h3><p>Cuba tajuk, genre atau koleksi lain.</p><button className="button button-outline" onClick={resetFilters}>Lihat semua karya <ArrowRight size={16} /></button></div>}{!showAll && filtered.length > 4 && <div className="catalog-more"><button className="button button-outline" onClick={() => setShowAll(true)}>Terokai semua {filtered.length} karya <ArrowDown size={16} /></button><span>Setiap cerita punya suaranya sendiri.</span></div>}</section>
      <section className="free-library-banner container" id="perpustakaan"><div><p className="eyebrow">PERPUSTAKAAN PERCUMA & BLOG</p><h2>Singgah, baca,<br /><em>dan bawa pulang rasa.</em></h2><p>Tiga bab pertama e-book, draf pitching dan cerpen mingguan. Anda juga boleh terus ke blog untuk zon bacaan percuma lengkap.</p><div className="free-banner-buttons"><button className="button button-cream" onClick={() => browse("library")}>Koleksi di laman ini <LibraryBig size={18} /></button><a className="button button-outline free-banner-blog-btn" href={profile.blogUrl || "https://mayamyrapenulisblog.blogspot.com/"} target="_blank" rel="noopener noreferrer">Zon Bacaan Percuma di Blog <ArrowUpRight size={16} /></a></div></div><div className="library-art" aria-hidden="true"><LibraryBig size={108} strokeWidth={.65} /><span>FREE<br />READING<br />SHELF</span></div></section>
      <section className="how-section container" id="cara"><div className="how-header"><div><p className="eyebrow">DARI KARYA KE CERITA ANDA</p><h2>Cerita anda, dalam tiga langkah.</h2></div><p>Mudah untuk ditemui.<br />Jelas untuk dimiliki.</p></div><div className="steps-grid"><article><span className="step-number">01</span><div className="step-icon"><Search size={22} strokeWidth={1.5} /></div><h3>Temui cerita anda</h3><p>Pilih Kedai Skrip atau Kedai E-Book. Baca sinopsis, petikan dan semak status karya.</p></article><article><span className="step-number">02</span><div className="step-icon"><Handshake size={23} strokeWidth={1.5} /></div><h3>Buy Now atau Hold</h3><p>Hantar permintaan pembelian atau tahan karya eksklusif sementara berbincang dengan penulis.</p></article><article><span className="step-number">03</span><div className="step-icon"><Clapperboard size={23} strokeWidth={1.5} /></div><h3>Hidupkan cerita</h3><p>Selepas jualan disahkan, fail karya dibuka untuk pembeli. Bacaan Percuma kekal terbuka untuk semua.</p></article></div></section>
      <section className="writer-callout container"><div><p className="eyebrow">SATU PENULIS, PELBAGAI CERITA</p><h2>Setiap halaman.<br />Sebuah kemungkinan.</h2><p>Dari manuskrip ke layar dan suara —<br />temui cerita yang dekat dengan anda.</p><a className="button button-cream" href="#karya">Terokai koleksi karya <ArrowUpRight size={18} /></a></div><div className="callout-art" aria-hidden="true"><span className="callout-orbit" /><div className="callout-page callout-page-back" /><div className="callout-page"><PenLine size={28} strokeWidth={1.2} /><span>Setiap cerita<br />bermula dengan<br /><em>satu halaman.</em></span><i /><i /><i /><small>MAYA MYRA STORIES</small></div><Sparkles className="callout-spark" size={39} strokeWidth={1} /></div></section>
      <section className="about-section container" id="tentang"><div className="about-quote"><span className="quote-mark">“</span><blockquote>Saya percaya cerita yang jujur akan sentiasa menemukan pembacanya.</blockquote><span className="author-signature">{author}</span><p>PENULIS DI SEBALIK CERITA</p></div><div className="about-copy"><p className="eyebrow">BUKAN SEKADAR SEBUAH HALAMAN</p><h2>Di sebalik setiap halaman,<br />ada sebuah harapan.</h2>{profile.bio ? <p style={{ whiteSpace: "pre-line" }}>{profile.bio}</p> : <><p>Ini ialah ruang peribadi seorang penulis — tempat untuk skrip produksi, e-book dan bahan bacaan percuma menemukan pembaca tanpa kehilangan suara asalnya.</p><p>Dari kisah cinta yang kecil hingga realiti kota yang besar, setiap karya ditulis untuk sesuatu yang lebih bermakna.</p></>}<a className="section-link" href="#karya">Cari cerita yang dekat dengan anda <ArrowUpRight size={17} /></a></div></section>
      {profile.blogUrl && <section className="blog-connection container"><div className="blog-connection-icon"><BookOpen size={29} strokeWidth={1.4} /></div><div><p className="eyebrow">CATATAN PERIBADI</p><h2>Singgah ke Laman Alam Maya.</h2><p>Cerpen, perjalanan menulis dan catatan di blog saya. Bacaan umum untuk anda yang sekadar ingin singgah.</p></div><a className="button button-outline" href={profile.blogUrl} target="_blank" rel="noopener noreferrer">Baca blog saya <ArrowUpRight size={16} /></a></section>}
      <section className="faq-section container" id="soalan"><div><p className="eyebrow">SEDIKIT PENJELASAN</p><h2>Mungkin anda tertanya-tanya.</h2><p>Semua yang perlu anda tahu sebelum memilih cerita.</p></div><div className="faq-list">{faqs.map((faq, index) => <article className={`faq-item${faqOpen === index ? " open" : ""}`} key={faq.question}><button onClick={() => setFaqOpen(faqOpen === index ? null : index)} aria-expanded={faqOpen === index}>{faq.question}<ChevronDown size={18} /></button>{faqOpen === index && <p>{faq.answer}</p>}</article>)}</div></section><Newsletter />
    </main><footer className="site-footer"><div className="footer-top container"><div><Brand /><p>Setiap cerita, sebuah kemungkinan.</p></div><nav aria-label="Navigasi kaki laman"><button onClick={() => browse("script")}>Kedai Skrip</button><button onClick={() => browse("ebook")}>Kedai E-Book</button><button onClick={() => browse("library")}>Perpustakaan Percuma</button><a href="#soalan">Soalan lazim</a>{profile.blogUrl && <a href={profile.blogUrl} target="_blank" rel="noopener noreferrer">Blog penulis <ArrowUpRight size={13} /></a>}{isOwner && <Link href="/studio">Ruang penulis <ArrowUpRight size={13} /></Link>}</nav><span className="footer-note"><PenLine size={15} /> Ditulis dengan rasa.</span></div><div className="footer-bottom container"><span>© {new Date().getFullYear()} Maya Myra Stories. Hak cipta terpelihara.</span><span>Hak karya kekal milik penulis sehingga dipersetujui secara bertulis.</span></div></footer>
    {dialog?.type === "detail" && <WorkDetail work={dialog.work} onClose={closeDialog} onOrder={openOrder} />}{dialog?.type === "order" && <OrderDialog key={`${dialog.work.id}-${dialog.action}`} work={dialog.work} type={dialog.action} onClose={closeDialog} onOrdered={markReserved} />}{dialog?.type === "saved" && <Modal title="Cerita yang anda simpan." eyebrow="SIMPAN UNTUK KEMUDIAN" onClose={closeDialog}>{visibleSaved.length ? <div className="saved-list">{works.filter((work) => saved.includes(work.id)).map((work) => <div className="saved-row" key={work.id}><button className="saved-row-main" onClick={() => setDialog({ type: "detail", work })}><img src={work.image} alt="" /><span><small>{work.format} · {work.genre}</small><strong>{work.title}</strong><span><StatusBadge status={work.status} isFree={work.isFree} /><b>{work.isFree ? "PERCUMA" : money(work.price)}</b></span></span><ArrowUpRight size={18} /></button><button className="icon-button" aria-label={`Buang ${work.title} daripada simpanan`} onClick={() => toggleSave(work.id)}><X size={16} /></button></div>)}</div> : <div className="saved-empty"><Bookmark size={37} strokeWidth={1.2} /><h3>Satu cerita akan menarik hati anda.</h3><p>Tekan ikon penanda pada mana-mana karya untuk menyimpannya di sini.</p><button className="button" onClick={closeDialog}>Terokai karya <ArrowRight size={16} /></button></div>}</Modal>}{toast && <Toast message={toast} onClose={closeToast} />}
  </>;
}
