"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, BadgeCheck, BookOpen, Bookmark, Check, ChevronDown, Clapperboard, FileCheck2, Handshake, Info, Loader2, Menu, PenLine, Search, ShieldCheck, SlidersHorizontal, Sparkles, UploadCloud, X } from "lucide-react";
import { Brand } from "./brand";
import { Modal, StatusBadge, Toast } from "./ui";
import { WorkCard } from "./work-card";
import { OrderDialog, WorkDetail } from "./work-dialogs";
import { errorMessage, requestJSON } from "@/lib/client";
import { formats, genres, money, type PublicProfile, type PublicWork } from "@/lib/types";

type Dialog = { type: "detail"; work: PublicWork } | { type: "order"; work: PublicWork; action: "buy" | "hold" } | { type: "saved" } | null;

function HeroArtwork({ work, count, onOpen }: { work?: PublicWork; count: number; onOpen: () => void }) {
  return <div className="hero-artwork">
    <div className="artwork-grain" />
    <span className="scene-note">Cerita yang menunggu<br />untuk dihidupkan.</span>
    <span className="scene-edition">THE ORIGINAL<br />STORY COLLECTION</span>
    <svg className="scene-star" viewBox="0 0 70 70" fill="none" aria-hidden="true"><path d="M35 3v64M3 35h64M12.4 12.4l45.2 45.2m0-45.2L12.4 57.6M22.7 5.4l24.6 59.2M5.4 22.7l59.2 24.6m0-24.6L5.4 47.3M47.3 5.4 22.7 64.6" stroke="currentColor" strokeWidth="1.2" /></svg>
    <div className="paper-back paper-back-one"><span>NASKAH ORIGINAL</span><i /><i /><i /><i /><i /></div><div className="paper-back paper-back-two" />
    <button className="hero-manuscript" onClick={onOpen} aria-label={`Pratonton ${work?.title || "naskah pilihan"}`}><span className="paper-topline"><span>NASKAH ORIGINAL</span><span>NO. 001</span></span><span className="paper-category">{work?.format.toUpperCase() || "TELEMOVIE"}</span><span className="paper-title">{work?.title === "Antara Dua Senja" ? <>Antara Dua<br />Senja.</> : work?.title || <>Antara Dua<br />Senja.</>}</span><span className="paper-description">SEBUAH CERITA TENTANG PULANG.</span><img className="paper-photo" src={work?.image || "/images/senja.jpg"} alt="Kulit naskah pilihan" /><span className="paper-footer"><span>OLEH {work?.author.toUpperCase() || "ALYA RAHMAN"}</span><span>01 — {String(count).padStart(2, "0")}</span></span></button>
    <svg className="scene-leaf" viewBox="0 0 150 175" fill="none" aria-hidden="true"><path d="M28 165C53 140 71 107 91 24" stroke="currentColor" strokeWidth="1.5" /><path d="M60 123C28 117 20 102 15 83c32 0 48 14 45 40Zm13-29C39 84 42 67 44 53c26 9 36 22 29 41Zm10-32C64 40 71 24 84 11c13 21 17 35-1 51Zm-27 75c37 0 51-10 67-31-31-10-54 4-67 31Zm20-40c30 2 50-13 57-35-26-4-45 10-57 35Zm12-34c28-6 35-22 36-40-23 5-34 18-36 40Z" fill="currentColor" fillOpacity=".14" stroke="currentColor" strokeWidth="1" /></svg>
    <div className="editor-note"><span><Sparkles size={13} /> PILIHAN PENULIS</span></div>
    <div className="original-note"><span className="original-icon"><FileCheck2 size={23} strokeWidth={1.5} /></span><div><strong>Karya asli. Cerita anda.</strong><span>Hak eksklusif, terus dari penulis.</span></div><BadgeCheck size={17} /></div>
  </div>;
}

function Newsletter() {
  const [loading, setLoading] = useState(false), [done, setDone] = useState(false), [error, setError] = useState("");
  async function subscribe(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError("");
    const email = new FormData(event.currentTarget).get("email");
    try { await requestJSON("/api/newsletter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); setDone(true); } catch (err) { setError(errorMessage(err)); } finally { setLoading(false); }
  }
  return <section className="newsletter-section container"><div><span className="eyebrow">SURAT KECIL DARI NASKAH</span><h2>Jangan terlepas cerita baharu.</h2><p>Daftarkan minat anda untuk kemas kini karya dan nota daripada penulis.</p></div><div className="newsletter-form-wrap">{done ? <div className="subscription-success" role="status"><Check size={22} /><div><strong>Anda sudah dalam senarai.</strong><span>Terima kasih kerana menjadi sebahagian daripada cerita ini.</span></div></div> : <form className="newsletter-form" onSubmit={subscribe}><label className="sr-only" htmlFor="newsletter-email">Alamat e-mel</label><input id="newsletter-email" name="email" type="email" placeholder="Alamat e-mel anda" maxLength={254} required /><button className="button" disabled={loading}>{loading ? <Loader2 size={17} className="spin" /> : <>Daftar minat <ArrowUpRight size={16} /></>}</button></form>}{error && <p className="form-error" role="alert">{error}</p>}<p className="newsletter-small">Hanya cerita yang baik. Tiada spam.</p></div></section>;
}

const faqs = [
  { question: "Apa perbezaan Buy, Hold dan Sold Out?", answer: "Buy menghantar permintaan pembelian kepada penulis. Hold memberi masa untuk anda berfikir sebelum membeli, mengikut tempoh yang tertera pada karya. Jika tempoh tamat tanpa pengesahan jualan, karya kembali tersedia. Sold Out bermaksud karya telah terjual dan tidak boleh ditempah lagi." },
  { question: "Bagaimana bayaran dan penyerahan karya dilakukan?", answer: "Selepas permintaan dihantar, penulis menyemaknya di Ruang Penulis. Bayaran dan perjanjian diurus secara terus dengan penulis — laman ini tidak memproses bayaran automatik. Selepas penulis mengesahkan penerimaan bayaran, pautan pesanan anda akan membuka muat turun fail karya." },
  { question: "Bolehkah saya membeli manuskrip novel separuh siap?", answer: "Boleh, jika penulis menawarkannya. Tahap siap ditunjukkan berasingan daripada status jualan. Baca sinopsis dan bincangkan bahagian yang diserahkan, sama ada penyempurnaan termasuk dalam harga, tarikh siap dan skop hak. Semua ini perlu dipersetujui secara bertulis sebelum pembayaran." },
  { question: "Apakah jenis karya di dalam koleksi ini?", answer: "Ini ialah laman peribadi seorang penulis, bukan marketplace ramai penulis. Koleksi menyokong manuskrip novel, telemovie, drama TV bersiri, skrip layar untuk filem panjang, drama radio dan filem pendek. Karya boleh ditandakan lengkap atau separuh siap." },
  { question: "Adakah hak eksklusif berpindah apabila saya menekan Buy?", answer: "Tidak. Menekan Buy atau Hold hanya menghantar permintaan. Skop hak adaptasi, kredit penulis dan pemindahan hak perlu dipersetujui secara bertulis. Membaca sinopsis atau petikan tidak memindahkan hak cipta." },
  { question: "Adakah lawatan atau klik bacaan terus menjana pendapatan?", answer: "Tidak secara automatik. Pendapatan iklan memerlukan rangkaian iklan seperti AdSense, laman yang diluluskan dan paparan atau interaksi iklan yang sah. Tiada kadar tetap bagi setiap pelawat dan pendapatan tidak dijamin. Iklan belum diaktifkan dalam contoh laman ini; Blogger sedia ada boleh terus digunakan untuk artikel dan permohonan AdSense." },
];

export function Marketplace({ initialWorks, profile }: { initialWorks: PublicWork[]; profile: PublicProfile }) {
  const [works, setWorks] = useState(initialWorks), [category, setCategory] = useState("Semua karya"), [query, setQuery] = useState("");
  const [genre, setGenre] = useState("all"), [status, setStatus] = useState("all"), [progress, setProgress] = useState("all"), [sort, setSort] = useState("recommended");
  const [showAll, setShowAll] = useState(false), [filtersOpen, setFiltersOpen] = useState(false), [mobileOpen, setMobileOpen] = useState(false);
  const [saved, setSaved] = useState<string[]>([]), [dialog, setDialog] = useState<Dialog>(null), [toast, setToast] = useState("");
  const [faqOpen, setFaqOpen] = useState<number | null>(null);
  const filterRef = useRef<HTMLDivElement>(null);
  const closeDialog = useCallback(() => setDialog(null), []);
  const closeToast = useCallback(() => setToast(""), []);
  useEffect(() => { try { const stored = JSON.parse(localStorage.getItem("naskah_saved") || "[]"); if (Array.isArray(stored)) setSaved(stored.filter((item) => typeof item === "string")); } catch { /* Browser storage is optional. */ } }, []);
  useEffect(() => {
    let active = true;
    const sync = () => {
      if (document.visibilityState !== "visible") return;
      requestJSON<{ works: PublicWork[] }>("/api/works").then((data) => {
        if (!active) return;
        setWorks(data.works);
        setDialog((current) => current?.type === "detail" ? { ...current, work: data.works.find((item) => item.id === current.work.id) || current.work } : current);
      }).catch(() => { /* Keep the existing catalog during a brief connection outage. */ });
    };
    const timer = setInterval(sync, 30000);
    window.addEventListener("focus", sync);
    return () => { active = false; clearInterval(timer); window.removeEventListener("focus", sync); };
  }, []);
  useEffect(() => { if (!filtersOpen) return; const close = (event: MouseEvent) => { if (!filterRef.current?.contains(event.target as Node)) setFiltersOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, [filtersOpen]);
  const visibleSaved = saved.filter((id) => works.some((work) => work.id === id));
  function toggleSave(id: string) {
    const next = saved.includes(id) ? saved.filter((item) => item !== id) : [...saved, id];
    setSaved(next); try { localStorage.setItem("naskah_saved", JSON.stringify(next)); } catch { /* Browser storage may be unavailable. */ }
    setToast(next.includes(id) ? "Naskah ditambah ke karya disimpan." : "Naskah dikeluarkan daripada simpanan.");
  }
  const filtered = useMemo(() => {
    const result = works.filter((work) => (category === "Semua karya" || work.format === category) && (genre === "all" || work.genre === genre) && (status === "all" || work.status === status) && (progress === "all" || work.progress === progress) && `${work.title} ${work.synopsis} ${work.genre} ${work.format} ${work.author} ${work.progress}`.toLowerCase().includes(query.toLowerCase().trim()));
    return result.sort((a, b) => sort === "price-asc" ? a.price - b.price : sort === "price-desc" ? b.price - a.price : sort === "newest" ? b.createdAt.localeCompare(a.createdAt) : Number(a.isDemo) - Number(b.isDemo) || Number(b.featured) - Number(a.featured) || b.createdAt.localeCompare(a.createdAt));
  }, [works, category, genre, status, progress, sort, query]);
  const visibleWorks = showAll ? filtered : filtered.slice(0, 4);
  const filterCount = Number(genre !== "all") + Number(status !== "all") + Number(progress !== "all");
  function resetFilters() { setCategory("Semua karya"); setGenre("all"); setStatus("all"); setProgress("all"); setQuery(""); setSort("recommended"); setShowAll(false); }
  function openOrder(work: PublicWork, action: "buy" | "hold") { setDialog({ type: "order", work, action }); }
  function markReserved(id: string) { setWorks((current) => current.map((work) => work.id === id ? { ...work, status: "hold" } : work)); }
  const author = profile.displayName || works[0]?.author || "Penulis Naskah";
  const hasExamples = works.some((work) => work.isDemo);

  return <>
    <header className="site-header"><div className="header-inner container"><Brand /><nav className="desktop-nav" aria-label="Navigasi utama"><a href="#karya" className="nav-link active">Terokai karya</a><a href="#cara" className="nav-link">Cara ia berfungsi</a><a href="#tentang" className="nav-link">Tentang penulis</a></nav><div className="header-actions"><button className="header-bookmark" aria-label={`Karya disimpan, ${visibleSaved.length} naskah`} onClick={() => setDialog({ type: "saved" })}><Bookmark size={20} strokeWidth={1.6} />{visibleSaved.length > 0 && <span>{visibleSaved.length}</span>}</button><span className="header-divider" /><Link className="button writer-link" href="/studio?upload=1"><UploadCloud size={15} />Upload skrip<ArrowUpRight size={16} /></Link><button className="icon-button mobile-menu-button" aria-label={mobileOpen ? "Tutup menu" : "Buka menu"} aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X size={23} /> : <Menu size={23} />}</button></div></div>{mobileOpen && <nav className="mobile-nav" aria-label="Navigasi mudah alih"><a href="#karya" onClick={() => setMobileOpen(false)}>Terokai karya</a><a href="#cara" onClick={() => setMobileOpen(false)}>Cara ia berfungsi</a><a href="#tentang" onClick={() => setMobileOpen(false)}>Tentang penulis</a>{profile.blogUrl && <a href={profile.blogUrl} target="_blank" rel="noopener noreferrer">Catatan di blog <ArrowUpRight size={16} /></a>}<Link href="/studio?upload=1"><UploadCloud size={16} />Upload skrip / ruang penulis</Link></nav>}</header>
    <main>
      <section className="hero-section"><div className="hero-inner container"><div className="hero-copy"><div className="hero-kicker"><span />DARI HALAMAN PERTAMA, KE CERITA ANDA</div><h1>Cerita yang baik,<br /><em>bermula di sini.</em></h1><p>Sebuah laman karya peribadi, untuk cerita yang bermakna.<br className="desktop-break" /> Novel, skrip TV, layar dan radio — terus daripada penulis.</p><div className="hero-buttons"><a className="button hero-primary" href="#karya">Terokai karya <ArrowUpRight size={18} /></a><Link className="hero-secondary" href="/studio?upload=1">Upload skrip saya <UploadCloud size={16} /></Link></div><div className="hero-stats"><div><strong>{String(works.length).padStart(2, "0")}<span>+</span></strong><span>Naskah pilihan</span></div><div><strong>{String(formats.length).padStart(2, "0")}</strong><span>Format cerita</span></div><div><strong>01</strong><span>Suara penulis</span></div></div></div><HeroArtwork work={works[0]} count={works.length} onOpen={() => { if (works[0]) setDialog({ type: "detail", work: works[0] }); }} /></div></section>
      <div className="trust-strip"><div className="container trust-inner"><span><BadgeCheck size={18} strokeWidth={1.5} />Karya asli, suara sendiri</span><span><ShieldCheck size={18} strokeWidth={1.5} />Hak cipta dilindungi</span><span><Handshake size={19} strokeWidth={1.5} />Terus daripada penulis</span><span><BookOpen size={18} strokeWidth={1.5} />Cerita dalam pelbagai bentuk</span></div></div>
      <section className="catalog-section container" id="karya"><div className="section-heading"><div><p className="eyebrow">KOLEKSI NASKAH</p><h2>Temui cerita seterusnya.</h2></div><button className="section-link" onClick={() => { resetFilters(); setShowAll(true); }}>Lihat semua karya <ArrowUpRight size={17} /></button></div>
        {hasExamples && <div className="demo-catalog-note"><Info size={13} /><span>Karya bertanda Contoh ialah demonstrasi. Upload skrip anda untuk membina koleksi sebenar.</span><Link href="/studio?upload=1">Upload skrip <ArrowUpRight size={12} /></Link></div>}
        <div className="catalog-toolbar"><div className="filter-tabs" aria-label="Format karya">{["Semua karya", ...formats].map((format) => <button key={format} className={`filter-tab${category === format ? " selected" : ""}`} onClick={() => { setCategory(format); setShowAll(format !== "Semua karya"); }} aria-pressed={category === format}>{format}{format === "Semua karya" && <span>{works.length}</span>}</button>)}</div><div className="catalog-tools"><div className="search-box"><Search size={17} strokeWidth={1.7} /><input aria-label="Cari naskah" placeholder="Cari tajuk, genre…" value={query} onChange={(event) => { setQuery(event.target.value); setShowAll(true); }} />{query && <button aria-label="Kosongkan carian" onClick={() => setQuery("")}><X size={14} /></button>}</div><div className="filter-wrap" ref={filterRef}><button className={`filter-button${filtersOpen || filterCount ? " filter-active" : ""}`} onClick={() => setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}><SlidersHorizontal size={16} />Tapis{filterCount > 0 && <span>{filterCount}</span>}</button>{filtersOpen && <div className="filter-popover"><h3>Temui naskah anda</h3><label className="field">Genre<select value={genre} onChange={(event) => { setGenre(event.target.value); setShowAll(true); }}><option value="all">Semua genre</option>{genres.map((item) => <option key={item}>{item}</option>)}</select></label><label className="field">Status karya<select value={status} onChange={(event) => { setStatus(event.target.value); setShowAll(true); }}><option value="all">Semua status</option><option value="available">Tersedia</option><option value="hold">On Hold</option><option value="sold">Sold Out</option></select></label><label className="field">Tahap siap<select value={progress} onChange={(event) => { setProgress(event.target.value); setShowAll(true); }}><option value="all">Semua tahap</option><option value="Lengkap">Lengkap</option><option value="Separuh siap">Separuh siap</option></select></label><label className="field">Susunan<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="recommended">Pilihan penulis</option><option value="newest">Paling baharu</option><option value="price-asc">Harga: rendah ke tinggi</option><option value="price-desc">Harga: tinggi ke rendah</option></select></label><div className="filter-popover-footer"><button onClick={resetFilters}>Set semula</button><button className="button" onClick={() => setFiltersOpen(false)}>Lihat {filtered.length} karya <Check size={14} /></button></div></div>}</div></div></div>
        {(query || filterCount > 0) && <div className="filter-results"><span>{filtered.length} naskah ditemui{query && <> untuk “{query}”</>}</span><button onClick={resetFilters}>Kosongkan penapis <X size={12} /></button></div>}
        {visibleWorks.length ? <div className="works-grid">{visibleWorks.map((work) => <WorkCard key={work.id} work={work} saved={saved.includes(work.id)} onSave={toggleSave} onDetail={(selected) => setDialog({ type: "detail", work: selected })} onOrder={openOrder} />)}</div> : <div className="catalog-empty"><Search size={33} strokeWidth={1.3} /><h3>Belum bertemu cerita yang tepat?</h3><p>Cuba tajuk atau genre lain, atau kosongkan penapis anda.</p><button className="button button-outline" onClick={resetFilters}>Lihat semua naskah <ArrowRight size={16} /></button></div>}
        {!showAll && filtered.length > 4 && <div className="catalog-more"><button className="button button-outline" onClick={() => setShowAll(true)}>Terokai semua {filtered.length} karya <ArrowDown size={16} /></button><span>Setiap cerita punya suaranya sendiri.</span></div>}
      </section>
      <section className="how-section container" id="cara"><div className="how-header"><div><p className="eyebrow">DARI NASKAH KE CERITA ANDA</p><h2>Cerita anda, dalam tiga langkah.</h2></div><p>Mudah untuk ditemui.<br />Jelas untuk dimiliki.</p></div><div className="steps-grid"><article><span className="step-number">01</span><div className="step-icon"><Search size={22} strokeWidth={1.5} /></div><h3>Temui cerita anda</h3><p>Terokai koleksi, baca sinopsis dan petikan. Semak format, genre dan tahap siap karya sebelum memilih.</p></article><article><span className="step-number">02</span><div className="step-icon"><Handshake size={23} strokeWidth={1.5} /></div><h3>Tempah dengan yakin</h3><p>Pilih Buy atau Hold mengikut masa yang tertera. Berbincang terus dengan penulis tentang bayaran dan hak karya.</p></article><article><span className="step-number">03</span><div className="step-icon"><Clapperboard size={23} strokeWidth={1.5} /></div><h3>Beri cerita sebuah pentas</h3><p>Selepas jualan disahkan, muat turun fail karya. Dari halaman novel ke layar, atau suara di gelombang radio.</p></article></div></section>
      <section className="writer-callout container"><div><p className="eyebrow">RUANG PERIBADI PENULIS</p><h2>Skrip anda.<br />Sedia untuk ditemukan.</h2><p>Upload fail, tetapkan harga dan urus tempahan —<br />semuanya di ruang penulis anda.</p><Link className="button button-cream" href="/studio?upload=1">Upload skrip saya <UploadCloud size={18} /></Link></div><div className="callout-art" aria-hidden="true"><span className="callout-orbit" /><div className="callout-page callout-page-back" /><div className="callout-page"><PenLine size={28} strokeWidth={1.2} /><span>Setiap cerita<br />bermula dengan<br /><em>satu halaman.</em></span><i /><i /><i /><small>NASKAH ORIGINAL</small></div><Sparkles className="callout-spark" size={39} strokeWidth={1} /></div></section>
      <section className="about-section container" id="tentang"><div className="about-quote"><span className="quote-mark">“</span><blockquote>Saya percaya cerita yang jujur akan sentiasa menemukan pembacanya.</blockquote><span className="author-signature">{author}</span><p>PENULIS DI SEBALIK NASKAH</p></div><div className="about-copy"><p className="eyebrow">BUKAN SEKADAR SEBUAH HALAMAN</p><h2>Di sebalik setiap halaman,<br />ada sebuah harapan.</h2>{profile.bio ? <p style={{ whiteSpace: "pre-line" }}>{profile.bio}</p> : <><p>Ini ialah ruang peribadi seorang penulis — tempat untuk manuskrip dan skrip asli menemukan pembaca, penerbit serta pembikin cerita, tanpa kehilangan suara asalnya.</p><p>Dari kisah keluarga yang dekat di hati, hingga misteri yang membuat kita berfikir — setiap naskah ditulis untuk sesuatu yang lebih besar.</p></>}<a className="section-link" href="#karya">Cari cerita yang dekat dengan anda <ArrowUpRight size={17} /></a></div></section>
      {profile.blogUrl && <section className="blog-connection container"><div className="blog-connection-icon"><BookOpen size={29} strokeWidth={1.4} /></div><div><p className="eyebrow">CATATAN PERIBADI</p><h2>{profile.blogUrl === "https://mayamyrapenulisblog.blogspot.com/" ? "Singgah ke Laman Alam Maya." : "Di luar naskah, cerita diteruskan."}</h2><p>Cerpen, perjalanan menulis dan catatan di blog saya. Bacaan umum untuk anda yang sekadar ingin singgah.</p></div><a className="button button-outline" href={profile.blogUrl} target="_blank" rel="noopener noreferrer">Baca blog saya <ArrowUpRight size={16} /></a></section>}
      <section className="faq-section container" id="soalan"><div><p className="eyebrow">SEDIKIT PENJELASAN</p><h2>Mungkin anda tertanya-tanya.</h2><p>Semua yang perlu anda tahu sebelum memilih cerita.</p></div><div className="faq-list">{faqs.map((faq, index) => <article className={`faq-item${faqOpen === index ? " open" : ""}`} key={faq.question}><button onClick={() => setFaqOpen(faqOpen === index ? null : index)} aria-expanded={faqOpen === index}>{faq.question}<ChevronDown size={18} /></button>{faqOpen === index && <p>{faq.answer}</p>}</article>)}</div></section>
      <Newsletter />
    </main>
    <footer className="site-footer"><div className="footer-top container"><div><Brand /><p>Setiap naskah, sebuah kemungkinan.</p></div><nav aria-label="Navigasi kaki laman"><a href="#karya">Koleksi karya</a><a href="#cara">Cara membeli</a><a href="#soalan">Soalan lazim</a>{profile.blogUrl && <a href={profile.blogUrl} target="_blank" rel="noopener noreferrer">Blog penulis <ArrowUpRight size={13} /></a>}<Link href="/studio">Ruang penulis <ArrowUpRight size={13} /></Link></nav><span className="footer-note"><PenLine size={15} /> Ditulis dengan rasa.</span></div><div className="footer-bottom container"><span>© {new Date().getFullYear()} Naskah. Hak cipta terpelihara.</span><span>Hak karya kekal milik penulis sehingga dipersetujui secara bertulis.</span></div></footer>
    {dialog?.type === "detail" && <WorkDetail work={dialog.work} onClose={closeDialog} onOrder={openOrder} />}
    {dialog?.type === "order" && <OrderDialog key={`${dialog.work.id}-${dialog.action}`} work={dialog.work} type={dialog.action} onClose={closeDialog} onOrdered={markReserved} />}
    {dialog?.type === "saved" && <Modal title="Cerita yang anda simpan." eyebrow="SIMPAN UNTUK KEMUDIAN" onClose={closeDialog}>{visibleSaved.length ? <div className="saved-list">{works.filter((work) => saved.includes(work.id)).map((work) => <div className="saved-row" key={work.id}><button className="saved-row-main" onClick={() => setDialog({ type: "detail", work })}><img src={work.image} alt="" /><span><small>{work.format} · {work.genre}</small><strong>{work.title}</strong><span><StatusBadge status={work.status} /><b>{money(work.price)}</b></span></span><ArrowUpRight size={18} /></button><button className="icon-button" aria-label={`Buang ${work.title} daripada simpanan`} onClick={() => toggleSave(work.id)}><X size={16} /></button></div>)}</div> : <div className="saved-empty"><Bookmark size={37} strokeWidth={1.2} /><h3>Satu cerita akan menarik hati anda.</h3><p>Tekan ikon penanda pada mana-mana naskah untuk menyimpannya di sini.</p><button className="button" onClick={closeDialog}>Terokai karya <ArrowRight size={16} /></button></div>}</Modal>}
    {toast && <Toast message={toast} onClose={closeToast} />}
  </>;
}
