"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import { ArrowRight, ArrowUpRight, BookOpen, CheckCircle2, Clock3, FileText, Film, Headphones, Info, LibraryBig, Loader2, ShieldCheck } from "lucide-react";
import { hasEpisodes, holdLabel, money, workLength, type PublicWork } from "@/lib/types";
import { errorMessage, requestJSON } from "@/lib/client";
import { Modal, StatusBadge } from "./ui";

export function WorkContent({ work, onOrder, pageLink = false }: { work: PublicWork; onOrder: (work: PublicWork, type: "buy" | "hold") => void; pageLink?: boolean }) {
  const [tab, setTab] = useState<"synopsis" | "excerpt">("synopsis");
  return <div className="detail-layout">
    <div className="detail-poster"><img src={work.image} alt={`Kulit ${work.title}`} /><div className="detail-poster-shade" /><span className="detail-poster-format">{work.isFree ? "PERPUSTAKAAN PERCUMA" : work.format.toUpperCase()}</span><div className="detail-poster-title">{work.title}<span>SEBUAH KARYA OLEH<br />{work.author.toUpperCase()}</span></div></div>
    <div className="detail-content"><div className="detail-topline"><StatusBadge status={work.status} isFree={work.isFree} /><span>{work.genre}{work.progress === "Separuh siap" ? " · Separuh siap" : ""}</span></div><h3>{work.title}</h3><p className="detail-author">Ditulis oleh {work.author}</p>
      <div className="detail-facts"><div><FileText size={17} /><strong>{work.pages}</strong><span>halaman</span></div><div>{work.section === "ebook" ? <BookOpen size={17} /> : work.format === "Drama Radio" ? <Headphones size={17} /> : work.isFree ? <LibraryBig size={17} /> : <Film size={17} />}<strong>{hasEpisodes(work.format) ? work.episodes : 1}</strong><span>{hasEpisodes(work.format) ? "episod" : work.isFree ? "bacaan" : "karya"}</span></div><div>{work.section === "script" ? <Clock3 size={17} /> : <BookOpen size={17} />}<strong>{work.section === "script" ? `${work.duration} min` : work.progress}</strong><span>{work.section === "script" ? `durasi${work.episodes > 1 ? " / episod" : ""}` : "tahap siap"}</span></div></div>
      <div className="detail-tabs" role="tablist" aria-label="Maklumat karya"><button role="tab" aria-selected={tab === "synopsis"} onClick={() => setTab("synopsis")} className={tab === "synopsis" ? "active" : ""}>Sinopsis</button><button role="tab" aria-selected={tab === "excerpt"} onClick={() => setTab("excerpt")} className={tab === "excerpt" ? "active" : ""}>Pratonton {work.section === "script" ? "skrip" : "bacaan"} <FileText size={13} /></button></div>
      <div className="detail-tab-content" role="tabpanel">{tab === "synopsis" ? <p>{work.synopsis}</p> : <pre className="script-excerpt">{work.excerpt || "Pratonton belum ditambah."}</pre>}</div>
      {work.isFree && <div className="info-note free-library-note"><LibraryBig size={17} /><p><strong>Bahan bacaan percuma.</strong> Tekan Baca Percuma untuk membuka fail. Tiada tempahan, Buy atau Hold diperlukan.</p></div>}
      {!work.isFree && work.progress === "Separuh siap" && <div className="info-note draft-note"><Info size={17} /><p><strong>Karya ini belum lengkap.</strong> Harga merujuk kepada draf yang tersedia. Bahagian akan datang perlu dipersetujui sebelum membeli.</p></div>}
      {!work.isFree && <div className="rights-note"><ShieldCheck size={18} /><p><strong>Satu karya. Satu pemilik.</strong><span>Pemindahan hak eksklusif tertakluk kepada persetujuan bertulis dengan penulis.</span><span>Hold memberi masa {holdLabel(work.holdHours)} untuk membuat keputusan.</span></p></div>}
      <div className="detail-purchase">{work.isFree ? <div><span>Akses bahan</span><strong>PERCUMA</strong></div> : <div><span>{work.progress === "Separuh siap" ? "Harga draf karya" : "Harga karya"}</span><strong>{money(work.price)}</strong></div>}{work.isFree ? <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}><a className="button" href={`/api/free/${encodeURIComponent(work.id)}`} target="_blank" rel="noopener noreferrer">Baca Di Sini <ArrowUpRight size={16} /></a><a className="button button-outline" href="https://mayamyrapenulisblog.blogspot.com/" target="_blank" rel="noopener noreferrer">Zon Bacaan Percuma di Blog <ArrowUpRight size={16} /></a></div> : work.status === "available" ? <div><button className="button" onClick={() => onOrder(work, "buy")}>BUY NOW <ArrowUpRight size={17} /></button><button className="button button-outline" onClick={() => onOrder(work, "hold")}>HOLD <Clock3 size={16} /></button></div> : <button className="button button-muted" disabled>{work.status === "hold" ? "HOLD" : "SOLD OUT"}</button>}</div>
      {pageLink && <Link className="detail-page-link" href={`/karya/${encodeURIComponent(work.id)}`}>Buka halaman karya untuk dikongsi <ArrowUpRight size={13} /></Link>}
    </div>
  </div>;
}

export function WorkDetail({ work, onClose, onOrder }: { work: PublicWork; onClose: () => void; onOrder: (work: PublicWork, type: "buy" | "hold") => void }) { return <Modal title="Di sebalik cerita." eyebrow={work.isFree ? "PERPUSTAKAAN PERCUMA" : "KENALI KARYA INI"} onClose={onClose} wide><WorkContent work={work} onOrder={onOrder} pageLink /></Modal>; }

type OrderResult = { reference: string; accessToken: string; expiresAt: string; holdHours: number };
export function OrderDialog({ work, type, onClose, onOrdered }: { work: PublicWork; type: "buy" | "hold"; onClose: () => void; onOrdered: (id: string) => void }) {
  const [loading, setLoading] = useState(false), [error, setError] = useState(""), [result, setResult] = useState<OrderResult | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); try { const response = await requestJSON<OrderResult>("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ manuscriptId: work.id, type, name: data.get("name"), email: data.get("email"), phone: data.get("phone"), notes: data.get("notes") }) }); setResult(response); onOrdered(work.id); } catch (err) { setError(errorMessage(err)); } finally { setLoading(false); } }
  return <Modal title={result ? "Cerita ini selangkah lebih dekat." : type === "buy" ? "Jadikan cerita ini milik anda." : "Simpan tempat untuk cerita ini."} eyebrow={result ? "PERMINTAAN DITERIMA" : type === "buy" ? "BUY NOW — PERMINTAAN PEMBELIAN" : `HOLD ${holdLabel(work.holdHours).toUpperCase()}`} onClose={onClose}>
    {result ? <div className="order-success"><div className="success-icon"><CheckCircle2 size={38} strokeWidth={1.5} /></div><h3>Terima kasih atas minat anda.</h3><p><strong>{work.title}</strong> ditahan untuk anda selama {holdLabel(result.holdHours)}. Penulis akan menyemak permintaan anda.</p><div className="order-reference"><span>Nombor rujukan</span><strong>{result.reference}</strong></div><div className="info-note"><Info size={17} /><p>Bayaran belum diproses pada laman ini. Penulis akan mengesahkan bayaran dan hak karya sebelum pautan muat turun dibuka.</p></div><Link className="button full-width" href={`/pesanan/${result.accessToken}`}>Lihat status pesanan <ArrowRight size={17} /></Link><button className="text-button" onClick={onClose}>Kembali ke katalog</button></div> : <form onSubmit={submit} className="order-form"><div className="order-summary"><img src={work.image} alt="" /><div><span>{work.format} · {work.genre}</span><h3>{work.title}</h3><p>{workLength(work)} · {work.pages} halaman</p></div><strong>{money(work.price)}</strong></div><div className="info-note"><Clock3 size={18} /><p>{type === "hold" ? `Karya ditahan selama ${holdLabel(work.holdHours)} tanpa caj untuk anda berfikir atau berbincang dengan penulis.` : `BUY NOW menghantar permintaan pembelian kepada penulis. Karya ditahan selama ${holdLabel(work.holdHours)} sementara bayaran dan hak penggunaan diselaraskan.`}</p></div>{work.progress === "Separuh siap" && <div className="info-note draft-note"><Info size={17} /><p>Anda sedang menempah karya separuh siap. Bincangkan skop penyerahan sebelum membayar.</p></div>}<div className="form-grid"><label className="field">Nama penuh <span>*</span><input name="name" autoComplete="name" placeholder="Nama anda atau syarikat" minLength={2} maxLength={80} required /></label><label className="field">Alamat e-mel <span>*</span><input name="email" type="email" autoComplete="email" placeholder="anda@email.com" maxLength={254} required /></label></div><label className="field">Nombor telefon <small>(pilihan)</small><input name="phone" type="tel" autoComplete="tel" placeholder="Contoh: 012-345 6789" maxLength={40} /></label><label className="field">Nota kepada penulis <small>(pilihan)</small><textarea name="notes" placeholder="Kongsikan sedikit tentang projek atau pertanyaan anda…" rows={3} maxLength={1500} /></label><label className="checkbox-field"><input type="checkbox" required /><span>Saya faham bahawa ini ialah permintaan pembelian atau Hold, bukan bayaran automatik. Hak karya belum dipindahkan.</span></label>{error && <p className="form-error" role="alert">{error}</p>}<button type="submit" className="button full-width" disabled={loading}>{loading ? <><Loader2 className="spin" size={17} /> Menghantar…</> : <>Hantar permintaan {type === "hold" ? "HOLD" : "BUY NOW"} <ArrowUpRight size={17} /></>}</button><p className="form-security"><ShieldCheck size={13} /> Maklumat anda hanya boleh dilihat oleh penulis.</p></form>}
  </Modal>;
}
