import dotenv from "dotenv";
import { chromium, request } from "playwright";
import { expect } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { sql } from "drizzle-orm";

dotenv.config({ quiet: true });
const base = process.env.NASKAH_TEST_URL || "http://localhost:3000";
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);
const suffix = randomUUID().slice(0, 8);
const writerEmail = `upload-owner-${suffix}@example.com`;
const buyerEmail = `upload-buyer-${suffix}@example.com`;
const title = `Skrip Upload Ujian ${suffix}`;
const marker = `PRIVATE-SCRIPT-${randomUUID()}`;
const password = randomUUID();
let browser, anonymous, createdOwner = false, before = [];
function check(label, result) { if (!result) throw new Error(`FAILED: ${label}`); console.log(`PASS: ${label}`); }

async function verify() {
  try {
    anonymous = await request.newContext({ baseURL: base });
    const initialCatalog = (await (await anonymous.get("/api/works")).json()).works;
    check("Catalog is active and public", initialCatalog.length >= 12);
    check("Anonymous bulk archive is denied", (await anonymous.delete("/api/studio/examples")).status() === 401);
    browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
    const owner = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const buyer = await browser.newPage({ viewport: { width: 1280, height: 950 } });
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
    const errors = [];
    for (const page of [owner, buyer, mobile]) page.on("pageerror", (error) => errors.push(error.message));
    await owner.goto(base, { waitUntil: "networkidle" });
    await owner.evaluate(() => document.fonts.ready);
    await expect(owner.locator('a[href^="/studio"]')).toHaveCount(0);
    await expect(owner.getByRole("link", { name: "Terokai koleksi karya" })).toBeVisible();
    check("Visitors see no upload or owner links in header, hero, callout or footer", true);
    check("Anonymous upload is rejected by the server", (await anonymous.post("/api/works", { multipart: { title: "Unauthorized upload" } })).status() === 401);
    check("Fake owner cookie cannot authorize an upload", (await anonymous.post("/api/works", { headers: { Cookie: "mayamyrastories_writer=fake-owner" }, multipart: { title: "Fake owner upload" } })).status() === 401);
    check("Anonymous script edits are rejected", (await anonymous.patch(`/api/works/${initialCatalog[0].id}`, { data: { status: "sold" } })).status() === 401);
    check("Anonymous script deletion is rejected", (await anonymous.delete(`/api/works/${initialCatalog[0].id}`)).status() === 401);
    await mobile.goto(base, { waitUntil: "networkidle" });
    await expect(mobile.locator('a[href^="/studio"]')).toHaveCount(0);
    check("Upload controls are absent from the visitor phone layout", true);
    check("Phone catalog has no horizontal overflow", await mobile.evaluate(() => document.documentElement.scrollWidth === innerWidth));
    await mobile.getByRole("button", { name: "Buka menu", exact: true }).click();
    await expect(mobile.locator(".mobile-nav")).toBeVisible();
    await expect(mobile.locator('.mobile-nav a[href^="/studio"]')).toHaveCount(0);
    check("Visitor mobile menu contains no management link", true);
    await mobile.goto(`${base}/studio?upload=1`, { waitUntil: "networkidle" });
    await expect(mobile.locator(".writer-onboarding")).toBeVisible();
    await expect(mobile.locator('input[type="file"]')).toHaveCount(0);
    check("Opening the private route directly does not grant upload access", true);

    const auth = await (await anonymous.get("/api/auth")).json();
    if (!auth.needsSetup) { console.log("An owner already exists; private upload tests skipped without altering the account."); return; }
    before = (await db.execute(sql`select id, author, active from manuscripts`)).rows;
    await owner.goto(`${base}/studio?upload=1`, { waitUntil: "networkidle" });
    await expect(owner.getByLabel("Nama pena / nama penulis")).toHaveValue("Maya Myra");
    await owner.getByLabel("Alamat e-mel", { exact: true }).fill(writerEmail);
    await owner.getByLabel("Kata laluan", { exact: true }).fill(password);
    await owner.getByRole("button", { name: "Cipta ruang penulis", exact: true }).click();
    await expect(owner.getByRole("dialog")).toBeVisible();
    createdOwner = true;
    check("Creating an account from Upload opens the file form automatically", true);
    const dialog = owner.getByRole("dialog");
    await dialog.getByLabel(/^Tajuk karya/).fill(title);
    await dialog.getByLabel("Kategori format", { exact: true }).selectOption("Drama Bersiri Perdana");
    await dialog.getByLabel(/^Sinopsis/).fill("Drama tiga puluh episod tentang keluarga yang menyusun kembali kehidupan mereka setelah sebuah rahsia terungkap. Ini data sementara untuk ujian.");
    await dialog.getByLabel(/^Pratonton skrip/).fill("EPISOD 1\n\nINT. RUMAH — PAGI\n\nSebuah pintu terbuka.");
    await dialog.getByLabel(/^Harga \(RM\)/).fill("6800");
    await dialog.getByLabel(/^Jumlah halaman/).fill("800");
    await dialog.getByLabel(/^Jumlah episod/).fill("30");
    await dialog.getByLabel(/^Durasi/).fill("45");
    await dialog.getByLabel("Tempoh Hold", { exact: true }).selectOption("12");
    await dialog.getByLabel("Muat naik fail karya", { exact: true }).setInputFiles({ name: "skrip.exe", mimeType: "application/octet-stream", buffer: Buffer.from("invalid") });
    await expect(dialog.getByRole("alert")).toContainText("Pilih fail PDF");
    check("Unsupported script extensions are rejected before upload", true);
    const file = Buffer.from(`%PDF-1.4\n% ${marker}\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF`);
    await dialog.getByLabel("Muat naik fail karya", { exact: true }).setInputFiles({ name: "skrip-30-episod.pdf", mimeType: "application/pdf", buffer: file });
    await expect(dialog.locator(".file-dropzone")).toContainText("skrip-30-episod.pdf");
    await dialog.getByRole("button", { name: "Terbitkan karya", exact: true }).click();
    await expect(owner.getByRole("dialog")).toHaveCount(0);
    await expect(owner.locator(".published-notice")).toContainText(title);
    await expect(owner.getByRole("link", { name: "Lihat karya saya" })).toBeVisible();
    check("Upload success shows a real work link", true);
    const uploadedCatalog = (await (await anonymous.get("/api/works")).json()).works;
    const uploaded = uploadedCatalog.find((work) => work.title === title);
    check("Uploaded PDF is stored with 30 episodes and 12-hour Hold", uploaded && uploaded.hasFile && uploaded.episodes === 30 && uploaded.holdHours === 12);
    check("Public catalog never exposes the PDF", !JSON.stringify(uploadedCatalog).includes(marker));
    const original = await owner.request.get(`${base}/api/works/${uploaded.id}/file`);
    check("Owner receives the exact original PDF", original.status() === 200 && Buffer.compare(await original.body(), file) === 0);
    check("Anonymous visitors cannot download the owner's PDF", (await anonymous.get(`/api/works/${uploaded.id}/file`)).status() === 401);

    const ownerHomeContext = await browser.newContext({ storageState: await owner.context().storageState() });
    const ownerHome = await ownerHomeContext.newPage();
    ownerHome.on("pageerror", (error) => errors.push(error.message));
    await ownerHome.goto(base, { waitUntil: "networkidle" });
    await expect(ownerHome.locator(".header-actions .writer-link")).toBeVisible();
    check("Authenticated owner retains the private management entry", true);
    await ownerHomeContext.close();
    await buyer.goto(base, { waitUntil: "networkidle" });
    await expect(buyer.locator('a[href^="/studio"]')).toHaveCount(0);
    check("Owner login does not expose controls to another visitor", true);
    check("An existing owner prevents visitor writer registration", (await anonymous.post("/api/auth", { data: { action: "setup", name: "Visitor", email: buyerEmail, password } })).status() === 409);

    await buyer.goto(`${base}/karya/${uploaded.id}`, { waitUntil: "networkidle" });
    await expect(buyer.getByRole("button", { name: "BUY NOW", exact: true })).toBeVisible();
    await expect(buyer.getByRole("button", { name: "HOLD", exact: true })).toBeVisible();
    check("BUY NOW and HOLD are immediately available on the uploaded script", true);
    await buyer.getByRole("button", { name: "HOLD", exact: true }).click();
    const holdForm = buyer.getByRole("dialog");
    await expect(holdForm).toContainText("12 jam");
    await holdForm.getByLabel(/^Nama penuh/).fill("Pembeli Upload Ujian");
    await holdForm.getByLabel(/^Alamat e-mel/).fill(buyerEmail);
    await holdForm.locator(".checkbox-field input").check();
    await holdForm.getByRole("button", { name: "Hantar permintaan HOLD", exact: true }).click();
    await expect(buyer.getByText("Terima kasih atas minat anda.")).toBeVisible();
    const orderPath = await buyer.getByRole("link", { name: "Lihat status pesanan" }).getAttribute("href");
    const token = orderPath.split("/").pop();
    check("Held PDF remains protected", (await anonymous.get(`/api/download/${token}`)).status() === 403);
    await owner.getByRole("button", { name: "Semak permintaan terkini" }).click();
    await owner.getByRole("button", { name: /Permintaan pembeli/ }).click();
    const orderCard = owner.locator(".request-card").filter({ hasText: title });
    await expect(orderCard).toBeVisible();
    check("Buy/Hold request reaches the author's dashboard", true);
    await orderCard.getByRole("button", { name: "Sahkan jualan", exact: true }).click();
    await owner.getByRole("dialog").getByRole("button", { name: "Sahkan jualan", exact: true }).click();
    await expect(owner.getByRole("dialog")).toHaveCount(0);
    await expect(owner.locator(".request-card").filter({ hasText: title }).locator(".request-state")).toHaveText("Selesai");
    await buyer.goto(`${base}/karya/${uploaded.id}`, { waitUntil: "networkidle" });
    await expect(buyer.getByRole("button", { name: "SOLD OUT", exact: true })).toBeDisabled();
    check("Confirmed sale changes the public script to SOLD OUT", true);
    const delivered = await anonymous.get(`/api/download/${token}`);
    check("Confirmed buyer can download the exact original PDF", delivered.status() === 200 && Buffer.compare(await delivered.body(), file) === 0);
    check("Buyer download uses attachment delivery", delivered.headers()["content-disposition"].includes("skrip-30-episod.pdf"));

    await owner.getByRole("button", { name: "Log keluar", exact: true }).click();
    await expect(owner.getByRole("heading", { name: "Selamat kembali, penulis." })).toBeVisible();
    await owner.goto(base, { waitUntil: "networkidle" });
    await expect(owner.locator('a[href^="/studio"]')).toHaveCount(0);
    check("Logging out removes the owner's public management controls", true);
    check("Logged-out owner cannot upload", (await owner.request.post(`${base}/api/works`, { multipart: { title: "Logged out" } })).status() === 401);
    check("No browser runtime errors", errors.length === 0);
    console.log("DIRECT UPLOAD AND SALE CONFIRMATION TESTS COMPLETE");
  } finally {
    if (browser) await browser.close();
    if (anonymous) await anonymous.dispose();
    const matchingOwner = (await db.execute(sql`select id from writer_settings where email=${writerEmail}`)).rows;
    if (matchingOwner.length) {
      await db.execute(sql`delete from orders where email=${buyerEmail} or manuscript_id in (select id from manuscripts where title=${title})`);
      await db.execute(sql`delete from manuscripts where title=${title}`);
      for (const record of before) await db.execute(sql`update manuscripts set author=${record.author}, active=${record.active} where id=${record.id}`);
      await db.execute(sql`delete from writer_sessions`);
      await db.execute(sql`delete from writer_settings where email=${writerEmail}`);
      console.log("Temporary tests removed; collection restored and owner setup available.");
    }
    await pool.end();
  }
}
verify().catch((error) => { console.error(error); process.exitCode = 1; });
